### ISSUE TITLE
strange imports after npm install

### ISSUE THREAD

**Issue by bernhardreisenberger** [jhsware/inferno-popper#2]
Hi,

Just wanted to update to the newest version, and had some issues with it.
after npm install the files in the node_modules folder contained imports that can not be resolved:
e.g.

import _objectWithoutProperties from "/Users/jhsware/node/lerna-inferno-modules/packages/inferno-popper/node_modules/@babel/runtime/helpers/esm/objectWithoutProperties";

see this link for details: https://npm.runkit.com/inferno-popper/lib/Manager.js?t=1540277616755

**Comment by jhsware** [comment]
Obviously an error in the build process. I have had a similar issue but didn't realise it came from the generated code. I will look into it!

**Comment by jhsware** [comment]
I will look at this later Today.

**Comment by jhsware** [comment]
@bernhardreisenberger I have released a fix 6.0.2 and in case someone else stumbles upon this. I was using the "inferno-app" preset in .babelrc and it forced absolute paths in @babel/runtime imports.

**Comment by bernhardreisenberger** [comment]
Thank you very much. i have successfully tested it today.
fyi: it seams like you forgot to push your commit to github.

**Comment by jhsware** [comment]
Awesome! You are right, I have pushed the change now :)
